name: _error
timestamp: 1539160535
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1503514829
positions: {  }
sections:
  navigation: Navigation
  sidebar: Sidebar
  mainbar: Mainbar
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-8525: 'Custom HTML'
    custom-5592: 'Custom HTML'
    custom-6549: 'Contact Info'
    custom-8844: Link
    custom-6785: Social
  messages:
    system-messages-6091: 'System Messages'
  content:
    system-content-3910: 'Page Content'
  logo:
    logo-1897: Logo
  menu:
    menu-1494: Menu
  branding:
    branding-7808: Branding
  mobile-menu:
    mobile-menu-6646: 'Mobile Menu'
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-1897: logo-7657
    menu-1494: menu-5263
    branding-7808: branding-4929
    custom-6549: custom-2130
    custom-8844: custom-1567
    custom-6785: custom-4939
    mobile-menu-6646: mobile-menu-7330
