name: _offline
timestamp: 1539151643
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: default
  timestamp: 1503513947
positions: {  }
sections:
  navigation: Navigation
  sidebar: Sidebar
  mainbar: Mainbar
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-6168: Logo
  menu:
    menu-9820: Menu
  branding:
    branding-3915: Branding
  custom:
    custom-5115: 'Contact Info'
    custom-1064: Link
    custom-7367: Social
  mobile-menu:
    mobile-menu-3319: 'Mobile Menu'
  messages:
    system-messages-1411: 'System Messages'
  content:
    system-content-3081: 'Page Content'
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-6168: logo-7657
    menu-9820: menu-5263
    branding-3915: branding-4929
    custom-5115: custom-2130
    custom-1064: custom-1567
    custom-7367: custom-4939
    mobile-menu-3319: mobile-menu-7330
  36:
    sidebar: sidebar
    mainbar: mainbar
    aside: aside
    system-messages-1411: system-messages-4126
    system-content-3081: system-content-1246
