ordering:
  home: ''
  about-us: ''
  services: ''
  partners: ''
  customers: ''
  projects: ''
  careers: ''
  contact: ''
items:
  home:
    id: 101
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  about-us:
    id: 102
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  services:
    id: 103
  partners:
    id: 104
  customers:
    id: 105
  projects:
    id: 106
  careers:
    id: 107
  contact:
    id: 108
