name: 11
timestamp: 1540228720
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: default
  timestamp: 1539151380
positions: {  }
sections:
  navigation: Navigation
  sidebar: Sidebar
  mainbar: Mainbar
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-7657: Logo
  menu:
    menu-5263: Menu
  messages:
    system-messages-4126: 'System Messages'
  content:
    system-content-1246: 'Page Content'
  branding:
    branding-7652: Branding
  custom:
    custom-2638: 'Contact Info'
    custom-2821: Link
    custom-8134: Social
  mobile-menu:
    mobile-menu-7330: 'Mobile Menu'
inherit:
  default:
    navigation: navigation
    sidebar: sidebar
    mainbar: mainbar
    aside: aside
    footer: footer
    offcanvas: offcanvas
    logo-7657: logo-7657
    menu-5263: menu-5263
    system-messages-4126: system-messages-4126
    system-content-1246: system-content-1246
    branding-7652: branding-4929
    custom-2638: custom-2130
    custom-2821: custom-1567
    custom-8134: custom-4939
    mobile-menu-7330: mobile-menu-7330
